// Generated by scripts/generate-db-types.mjs from supabase/migrations. Do not edit.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: { PostgrestVersion: "13" };
  public: {
    Tables: {
      couple_invitations: {
        Row: {
          id: string;
          couple_id: string;
          invited_email: string;
          invited_by: string | null;
          token_hash: string;
          expires_at: string;
          accepted_at: string | null;
          accepted_by: string | null;
          cancelled_at: string | null;
          cancelled_by: string | null;
          last_sent_at: string;
          send_window_started_at: string;
          sends_in_window: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          couple_id: string;
          invited_email: string;
          invited_by?: string | null;
          token_hash: string;
          expires_at: string;
          accepted_at?: string | null;
          accepted_by?: string | null;
          cancelled_at?: string | null;
          cancelled_by?: string | null;
          last_sent_at?: string;
          send_window_started_at?: string;
          sends_in_window?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          couple_id?: string;
          invited_email?: string;
          invited_by?: string | null;
          token_hash?: string;
          expires_at?: string;
          accepted_at?: string | null;
          accepted_by?: string | null;
          cancelled_at?: string | null;
          cancelled_by?: string | null;
          last_sent_at?: string;
          send_window_started_at?: string;
          sends_in_window?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "couple_invitations_couple_id_fkey";
            columns: ["couple_id"];
            isOneToOne: false;
            referencedRelation: "couples";
            referencedColumns: ["id"];
          },
        ];
      };
      couple_members: {
        Row: {
          couple_id: string;
          user_id: string;
          role: string;
          avatar_path: string | null;
          joined_at: string;
        };
        Insert: {
          couple_id: string;
          user_id: string;
          role?: string;
          avatar_path?: string | null;
          joined_at?: string;
        };
        Update: {
          couple_id?: string;
          user_id?: string;
          role?: string;
          avatar_path?: string | null;
          joined_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "couple_members_couple_id_fkey";
            columns: ["couple_id"];
            isOneToOne: false;
            referencedRelation: "couples";
            referencedColumns: ["id"];
          },
        ];
      };
      couple_themes: {
        Row: {
          couple_id: string;
          name: string;
          primary_color: string;
          background_color: string;
          card_style: string;
          typography: string;
          background_style: string;
          layout: string;
          updated_at: string;
        };
        Insert: {
          couple_id: string;
          name?: string;
          primary_color?: string;
          background_color?: string;
          card_style?: string;
          typography?: string;
          background_style?: string;
          layout?: string;
          updated_at?: string;
        };
        Update: {
          couple_id?: string;
          name?: string;
          primary_color?: string;
          background_color?: string;
          card_style?: string;
          typography?: string;
          background_style?: string;
          layout?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "couple_themes_couple_id_fkey";
            columns: ["couple_id"];
            isOneToOne: true;
            referencedRelation: "couples";
            referencedColumns: ["id"];
          },
        ];
      };
      couples: {
        Row: {
          id: string;
          slug: string;
          name: string | null;
          display_title: string;
          description: string | null;
          story_began_on: string | null;
          cover_path: string | null;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          slug: string;
          name?: string | null;
          display_title?: string;
          description?: string | null;
          story_began_on?: string | null;
          cover_path?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          slug?: string;
          name?: string | null;
          display_title?: string;
          description?: string | null;
          story_began_on?: string | null;
          cover_path?: string | null;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
        ];
      };
      events: {
        Row: {
          id: string;
          couple_id: string;
          created_by: string | null;
          title: string;
          description: string | null;
          starts_at: string;
          ends_at: string | null;
          all_day: boolean;
          location: string | null;
          place_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          couple_id: string;
          created_by?: string | null;
          title: string;
          description?: string | null;
          starts_at: string;
          ends_at?: string | null;
          all_day?: boolean;
          location?: string | null;
          place_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          couple_id?: string;
          created_by?: string | null;
          title?: string;
          description?: string | null;
          starts_at?: string;
          ends_at?: string | null;
          all_day?: boolean;
          location?: string | null;
          place_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "events_couple_id_fkey";
            columns: ["couple_id"];
            isOneToOne: false;
            referencedRelation: "couples";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "events_place_id_couple_id_fkey";
            columns: ["place_id", "couple_id"];
            isOneToOne: false;
            referencedRelation: "places";
            referencedColumns: ["id", "couple_id"];
          },
        ];
      };
      journal_photos: {
        Row: {
          id: string;
          couple_id: string;
          journal_id: string;
          uploaded_by: string | null;
          storage_path: string;
          content_type: string;
          size_bytes: number | null;
          caption: string | null;
          created_at: string;
          thumb_path: string | null;
          width: number | null;
          height: number | null;
        };
        Insert: {
          id?: string;
          couple_id: string;
          journal_id: string;
          uploaded_by?: string | null;
          storage_path: string;
          content_type: string;
          size_bytes?: number | null;
          caption?: string | null;
          created_at?: string;
          thumb_path?: string | null;
          width?: number | null;
          height?: number | null;
        };
        Update: {
          id?: string;
          couple_id?: string;
          journal_id?: string;
          uploaded_by?: string | null;
          storage_path?: string;
          content_type?: string;
          size_bytes?: number | null;
          caption?: string | null;
          created_at?: string;
          thumb_path?: string | null;
          width?: number | null;
          height?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "journal_photos_couple_id_fkey";
            columns: ["couple_id"];
            isOneToOne: false;
            referencedRelation: "couples";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "journal_photos_journal_id_couple_id_fkey";
            columns: ["journal_id", "couple_id"];
            isOneToOne: false;
            referencedRelation: "journals";
            referencedColumns: ["id", "couple_id"];
          },
        ];
      };
      journal_reflections: {
        Row: {
          id: string;
          couple_id: string;
          journal_id: string;
          author_id: string;
          visibility: string;
          body: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          couple_id: string;
          journal_id: string;
          author_id: string;
          visibility?: string;
          body: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          couple_id?: string;
          journal_id?: string;
          author_id?: string;
          visibility?: string;
          body?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "journal_reflections_couple_id_author_id_fkey";
            columns: ["couple_id", "author_id"];
            isOneToOne: false;
            referencedRelation: "couple_members";
            referencedColumns: ["couple_id", "user_id"];
          },
          {
            foreignKeyName: "journal_reflections_couple_id_fkey";
            columns: ["couple_id"];
            isOneToOne: false;
            referencedRelation: "couples";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "journal_reflections_journal_id_couple_id_fkey";
            columns: ["journal_id", "couple_id"];
            isOneToOne: false;
            referencedRelation: "journals";
            referencedColumns: ["id", "couple_id"];
          },
        ];
      };
      journals: {
        Row: {
          id: string;
          couple_id: string;
          created_by: string | null;
          title: string;
          body: string | null;
          entry_date: string;
          mood: string | null;
          created_at: string;
          updated_at: string;
          scrapbook: Json | null;
          scrapbook_updated_at: string | null;
          scrapbook_updated_by: string | null;
        };
        Insert: {
          id?: string;
          couple_id: string;
          created_by?: string | null;
          title: string;
          body?: string | null;
          entry_date?: string;
          mood?: string | null;
          created_at?: string;
          updated_at?: string;
          scrapbook?: Json | null;
          scrapbook_updated_at?: string | null;
          scrapbook_updated_by?: string | null;
        };
        Update: {
          id?: string;
          couple_id?: string;
          created_by?: string | null;
          title?: string;
          body?: string | null;
          entry_date?: string;
          mood?: string | null;
          created_at?: string;
          updated_at?: string;
          scrapbook?: Json | null;
          scrapbook_updated_at?: string | null;
          scrapbook_updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "journals_couple_id_fkey";
            columns: ["couple_id"];
            isOneToOne: false;
            referencedRelation: "couples";
            referencedColumns: ["id"];
          },
        ];
      };
      letter_contents: {
        Row: {
          letter_id: string;
          couple_id: string;
          content: string;
          updated_at: string;
        };
        Insert: {
          letter_id: string;
          couple_id: string;
          content: string;
          updated_at?: string;
        };
        Update: {
          letter_id?: string;
          couple_id?: string;
          content?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "letter_contents_couple_id_fkey";
            columns: ["couple_id"];
            isOneToOne: false;
            referencedRelation: "couples";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "letter_contents_letter_id_couple_id_fkey";
            columns: ["letter_id", "couple_id"];
            isOneToOne: false;
            referencedRelation: "letters";
            referencedColumns: ["id", "couple_id"];
          },
        ];
      };
      letters: {
        Row: {
          id: string;
          couple_id: string;
          author_id: string;
          recipient_id: string;
          title: string;
          unlock_at: string;
          opened_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          couple_id: string;
          author_id: string;
          recipient_id: string;
          title: string;
          unlock_at: string;
          opened_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          couple_id?: string;
          author_id?: string;
          recipient_id?: string;
          title?: string;
          unlock_at?: string;
          opened_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "letters_couple_id_author_id_fkey";
            columns: ["couple_id", "author_id"];
            isOneToOne: false;
            referencedRelation: "couple_members";
            referencedColumns: ["couple_id", "user_id"];
          },
          {
            foreignKeyName: "letters_couple_id_fkey";
            columns: ["couple_id"];
            isOneToOne: false;
            referencedRelation: "couples";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "letters_couple_id_recipient_id_fkey";
            columns: ["couple_id", "recipient_id"];
            isOneToOne: false;
            referencedRelation: "couple_members";
            referencedColumns: ["couple_id", "user_id"];
          },
        ];
      };
      milestones: {
        Row: {
          id: string;
          couple_id: string;
          created_by: string | null;
          title: string;
          description: string | null;
          occurred_on: string;
          icon: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          couple_id: string;
          created_by?: string | null;
          title: string;
          description?: string | null;
          occurred_on: string;
          icon?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          couple_id?: string;
          created_by?: string | null;
          title?: string;
          description?: string | null;
          occurred_on?: string;
          icon?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "milestones_couple_id_fkey";
            columns: ["couple_id"];
            isOneToOne: false;
            referencedRelation: "couples";
            referencedColumns: ["id"];
          },
        ];
      };
      notes: {
        Row: {
          id: string;
          couple_id: string;
          author_id: string;
          visibility: string;
          title: string | null;
          body: string;
          pinned: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          couple_id: string;
          author_id: string;
          visibility?: string;
          title?: string | null;
          body: string;
          pinned?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          couple_id?: string;
          author_id?: string;
          visibility?: string;
          title?: string | null;
          body?: string;
          pinned?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notes_couple_id_author_id_fkey";
            columns: ["couple_id", "author_id"];
            isOneToOne: false;
            referencedRelation: "couple_members";
            referencedColumns: ["couple_id", "user_id"];
          },
          {
            foreignKeyName: "notes_couple_id_fkey";
            columns: ["couple_id"];
            isOneToOne: false;
            referencedRelation: "couples";
            referencedColumns: ["id"];
          },
        ];
      };
      place_journals: {
        Row: {
          couple_id: string;
          place_id: string;
          journal_id: string;
          created_at: string;
        };
        Insert: {
          couple_id: string;
          place_id: string;
          journal_id: string;
          created_at?: string;
        };
        Update: {
          couple_id?: string;
          place_id?: string;
          journal_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "place_journals_couple_id_fkey";
            columns: ["couple_id"];
            isOneToOne: false;
            referencedRelation: "couples";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "place_journals_journal_id_couple_id_fkey";
            columns: ["journal_id", "couple_id"];
            isOneToOne: false;
            referencedRelation: "journals";
            referencedColumns: ["id", "couple_id"];
          },
          {
            foreignKeyName: "place_journals_place_id_couple_id_fkey";
            columns: ["place_id", "couple_id"];
            isOneToOne: false;
            referencedRelation: "places";
            referencedColumns: ["id", "couple_id"];
          },
        ];
      };
      places: {
        Row: {
          id: string;
          couple_id: string;
          created_by: string | null;
          name: string;
          description: string | null;
          address: string | null;
          latitude: number | null;
          longitude: number | null;
          category: string;
          status: string;
          first_visited_on: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          couple_id: string;
          created_by?: string | null;
          name: string;
          description?: string | null;
          address?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          category?: string;
          status?: string;
          first_visited_on?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          couple_id?: string;
          created_by?: string | null;
          name?: string;
          description?: string | null;
          address?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          category?: string;
          status?: string;
          first_visited_on?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "places_couple_id_fkey";
            columns: ["couple_id"];
            isOneToOne: false;
            referencedRelation: "couples";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          display_name: string;
          birthday: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name: string;
          birthday?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string;
          birthday?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      accept_couple_invitation: { Args: { p_token: string; p_display_name?: string }; Returns: Json };
      cancel_couple_invitation: { Args: { p_invitation_id: string }; Returns: undefined };
      create_couple: { Args: { p_creator_name: string; p_partner_email: string; p_invite_token_hash: string; p_couple_name?: string; p_story_began_on?: string; p_invite_ttl_days?: number }; Returns: Json };
      create_couple_invitation: { Args: { p_couple_id: string; p_invited_email: string; p_token_hash: string; p_ttl_days?: number }; Returns: Json };
      create_letter: { Args: { p_couple_id: string; p_title: string; p_content: string; p_unlock_at: string }; Returns: string };
      delete_couple: { Args: { p_couple_id: string; p_confirmation: string }; Returns: undefined };
      get_auth_account_state: { Args: { p_email: string }; Returns: string };
      get_invitation_preview: { Args: { p_token: string }; Returns: Json };
      mark_letter_opened: { Args: { p_letter_id: string }; Returns: undefined };
      resend_couple_invitation: { Args: { p_invitation_id: string; p_token_hash: string; p_ttl_days?: number }; Returns: Json };
      update_letter: { Args: { p_letter_id: string; p_title: string; p_content: string; p_unlock_at: string }; Returns: undefined };
    };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};

type PublicSchema = Database["public"];
export type Tables<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Row"];
export type TablesInsert<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof PublicSchema["Tables"]> = PublicSchema["Tables"][T]["Update"];
