-- =============================================================================
-- Our Story — complete database schema
--
-- Generated by scripts/bundle-schema.mjs from supabase/migrations. Do not edit;
-- change the migrations and run `npm run db:bundle`.
--
-- Run ONCE, in the Supabase SQL editor, on a project that does not have these
-- tables yet. The whole script runs in a single transaction: if anything fails,
-- nothing is applied.
-- =============================================================================

begin;

-- >>> 20260917000100_core_schema.sql

-- =============================================================================
-- Our Story :: 0100 core schema
--
-- Tenant root:        public.couples
-- Tenant boundary:    couple_id (NOT NULL on every tenant-owned table)
-- Security boundary:  RLS + public.couple_members (see 0200_rls.sql)
--
-- Integrity rules that make cross-tenant references impossible at the data
-- layer (independent of RLS):
--   * Every child row that points at a parent row uses a COMPOSITE foreign key
--     (parent_id, couple_id) -> parent(id, couple_id). A row in couple A can
--     therefore never reference a journal/place/letter that lives in couple B.
--   * Every "authored by a member" column uses a composite foreign key
--     (couple_id, user_id) -> couple_members. Letters can only be addressed to
--     someone who is actually in the same couple.
--   * couple_id (and author columns) are immutable after insert (trigger).
--   * A couple can never have more than two members (trigger + row lock).
--   * Storage paths stored in the database must live under the row's own
--     couples/{couple_id}/... prefix (check constraints).
-- =============================================================================

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated, service_role;

-- -----------------------------------------------------------------------------
-- Generic helpers
-- -----------------------------------------------------------------------------

create or replace function private.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

-- Rejects changes to the columns named in TG_ARGV (e.g. couple_id, author_id).
-- Moving a row between tenants, or re-attributing authorship, is never allowed.
create or replace function private.guard_immutable_columns()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_column text;
begin
  foreach v_column in array tg_argv loop
    if (to_jsonb(new) -> v_column) is distinct from (to_jsonb(old) -> v_column) then
      raise exception 'immutable_column'
        using detail = format('%s.%s cannot be changed', tg_table_name, v_column);
    end if;
  end loop;
  return new;
end;
$$;

create or replace function private.try_uuid(p_value text)
returns uuid
language sql
immutable
set search_path = ''
as $$
  select case
    when p_value ~ '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
      then p_value::uuid
  end;
$$;

create or replace function private.slugify(p_value text)
returns text
language sql
immutable
set search_path = ''
as $$
  select coalesce(
    nullif(
      left(trim(both '-' from regexp_replace(lower(coalesce(p_value, '')), '[^a-z0-9]+', '-', 'g')), 40),
      ''
    ),
    'our-story'
  );
$$;

-- SHA-256 hex digest of an invitation token. Raw tokens are never stored.
create or replace function private.hash_invitation_token(p_token text)
returns text
language sql
immutable
set search_path = ''
as $$
  select encode(sha256(convert_to(p_token, 'UTF8')), 'hex');
$$;

-- -----------------------------------------------------------------------------
-- profiles  (USER-OWNED — not a tenant table)
-- -----------------------------------------------------------------------------

create table public.profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  display_name text not null check (char_length(btrim(display_name)) between 1 and 60),
  birthday     date,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute function private.set_updated_at();

-- -----------------------------------------------------------------------------
-- couples  (TENANT ROOT)
-- -----------------------------------------------------------------------------

create table public.couples (
  id             uuid primary key default gen_random_uuid(),
  -- Presentation/routing identifier only. NEVER used for authorization.
  slug           text not null unique
                 check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' and char_length(slug) between 3 and 64),
  -- Optional relationship name ("John & Kath"). When null the UI derives one
  -- from the partners' display names.
  name           text check (name is null or char_length(btrim(name)) between 1 and 80),
  display_title  text not null default 'Our Little World'
                 check (char_length(btrim(display_title)) between 1 and 80),
  description    text check (description is null or char_length(description) <= 500),
  story_began_on date,
  cover_path     text,
  created_by     uuid references auth.users (id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  -- Soft delete. A deleted couple is invisible to everyone (see
  -- private.is_couple_member). Hard purge is a separate, offline admin task.
  deleted_at     timestamptz,
  constraint couples_cover_path_scoped check (
    cover_path is null
    or cover_path ~ ('^couples/' || id::text || '/cover/[0-9a-f-]{36}\.(jpg|png|webp|gif|avif)$')
  )
);

create trigger couples_set_updated_at
  before update on public.couples
  for each row execute function private.set_updated_at();

create trigger couples_guard_immutable
  before update on public.couples
  for each row execute function private.guard_immutable_columns('id', 'slug', 'created_by', 'created_at');

-- -----------------------------------------------------------------------------
-- couple_members  (users <-> couples; a user may belong to many couples)
-- -----------------------------------------------------------------------------

create table public.couple_members (
  couple_id   uuid not null references public.couples (id) on delete cascade,
  user_id     uuid not null references auth.users (id) on delete cascade,
  role        text not null default 'partner' check (role in ('creator', 'partner')),
  -- Per-space avatar, stored under this couple's storage prefix.
  avatar_path text,
  joined_at   timestamptz not null default now(),
  primary key (couple_id, user_id),
  constraint couple_members_avatar_path_scoped check (
    avatar_path is null
    or avatar_path ~ ('^couples/' || couple_id::text || '/avatars/' || user_id::text
                      || '/[0-9a-f-]{36}\.(jpg|png|webp|gif|avif)$')
  )
);

create index couple_members_user_id_idx on public.couple_members (user_id);

create trigger couple_members_guard_immutable
  before update on public.couple_members
  for each row execute function private.guard_immutable_columns('couple_id', 'user_id', 'role', 'joined_at');

-- A couple consists of exactly two people. Lock the couple row so concurrent
-- invitation acceptances serialize, then count.
create or replace function private.enforce_couple_member_limit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform 1 from public.couples where id = new.couple_id for update;

  if (select count(*) from public.couple_members where couple_id = new.couple_id) >= 2 then
    raise exception 'couple_full'
      using detail = 'This space already has two members.';
  end if;

  return new;
end;
$$;

create trigger couple_members_enforce_limit
  before insert on public.couple_members
  for each row execute function private.enforce_couple_member_limit();

-- -----------------------------------------------------------------------------
-- couple_invitations
-- -----------------------------------------------------------------------------

create table public.couple_invitations (
  id                     uuid primary key default gen_random_uuid(),
  couple_id              uuid not null references public.couples (id) on delete cascade,
  invited_email          text not null check (
                           invited_email = lower(btrim(invited_email))
                           and invited_email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'
                           and char_length(invited_email) <= 254
                         ),
  invited_by             uuid references auth.users (id) on delete set null,
  -- SHA-256 hex of the raw token. The raw token only ever exists in the
  -- invitation link. Rotated on resend, which invalidates the previous link.
  token_hash             text not null unique check (token_hash ~ '^[0-9a-f]{64}$'),
  expires_at             timestamptz not null,
  accepted_at            timestamptz,
  accepted_by            uuid references auth.users (id) on delete set null,
  cancelled_at           timestamptz,
  cancelled_by           uuid references auth.users (id) on delete set null,
  -- Resend rate limiting (enforced in public.resend_couple_invitation).
  last_sent_at           timestamptz not null default now(),
  send_window_started_at timestamptz not null default now(),
  sends_in_window        integer not null default 1 check (sends_in_window >= 0),
  created_at             timestamptz not null default now(),
  constraint couple_invitations_single_outcome check (accepted_at is null or cancelled_at is null)
);

-- At most one open invitation per couple.
create unique index couple_invitations_one_open_per_couple
  on public.couple_invitations (couple_id)
  where accepted_at is null and cancelled_at is null;

create index couple_invitations_invited_email_idx
  on public.couple_invitations (invited_email)
  where accepted_at is null and cancelled_at is null;

create trigger couple_invitations_guard_immutable
  before update on public.couple_invitations
  for each row execute function private.guard_immutable_columns('couple_id', 'invited_email', 'invited_by', 'created_at');

-- -----------------------------------------------------------------------------
-- couple_themes  (one row per couple)
-- -----------------------------------------------------------------------------

create table public.couple_themes (
  couple_id        uuid primary key references public.couples (id) on delete cascade,
  name             text not null default 'paper'
                   check (name in ('paper', 'linen', 'blush', 'sage', 'midnight')),
  primary_color    text not null default '#b4553d' check (primary_color ~ '^#[0-9a-fA-F]{6}$'),
  background_color text not null default '#f6f0e6' check (background_color ~ '^#[0-9a-fA-F]{6}$'),
  card_style       text not null default 'soft'
                   check (card_style in ('soft', 'flat', 'outlined', 'elevated')),
  typography       text not null default 'editorial'
                   check (typography in ('editorial', 'modern', 'classic', 'handwritten')),
  background_style text not null default 'paper'
                   check (background_style in ('plain', 'paper', 'grain', 'gradient')),
  layout           text not null default 'comfortable'
                   check (layout in ('comfortable', 'compact')),
  updated_at       timestamptz not null default now()
);

create trigger couple_themes_set_updated_at
  before update on public.couple_themes
  for each row execute function private.set_updated_at();

create trigger couple_themes_guard_immutable
  before update on public.couple_themes
  for each row execute function private.guard_immutable_columns('couple_id');

-- -----------------------------------------------------------------------------
-- journals  (COUPLE-OWNED)
-- -----------------------------------------------------------------------------

create table public.journals (
  id         uuid primary key default gen_random_uuid(),
  couple_id  uuid not null references public.couples (id) on delete cascade,
  created_by uuid references auth.users (id) on delete set null,
  title      text not null check (char_length(btrim(title)) between 1 and 160),
  body       text check (body is null or char_length(body) <= 50000),
  entry_date date not null default current_date,
  mood       text check (mood is null or char_length(mood) <= 40),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, couple_id)
);

create index journals_couple_entry_date_idx on public.journals (couple_id, entry_date desc);

create trigger journals_set_updated_at
  before update on public.journals
  for each row execute function private.set_updated_at();

create trigger journals_guard_immutable
  before update on public.journals
  for each row execute function private.guard_immutable_columns('couple_id', 'created_by', 'created_at');

-- -----------------------------------------------------------------------------
-- journal_reflections  (USER-OWNED when private, RELATIONSHIP-CONTROLLED when shared)
-- -----------------------------------------------------------------------------

create table public.journal_reflections (
  id         uuid primary key default gen_random_uuid(),
  couple_id  uuid not null references public.couples (id) on delete cascade,
  journal_id uuid not null,
  author_id  uuid not null,
  visibility text not null default 'shared' check (visibility in ('private', 'shared')),
  body       text not null check (char_length(btrim(body)) between 1 and 20000),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (journal_id, couple_id) references public.journals (id, couple_id) on delete cascade,
  foreign key (couple_id, author_id) references public.couple_members (couple_id, user_id) on delete cascade
);

create index journal_reflections_journal_idx on public.journal_reflections (journal_id);
create index journal_reflections_couple_author_idx on public.journal_reflections (couple_id, author_id);

create trigger journal_reflections_set_updated_at
  before update on public.journal_reflections
  for each row execute function private.set_updated_at();

create trigger journal_reflections_guard_immutable
  before update on public.journal_reflections
  for each row execute function private.guard_immutable_columns('couple_id', 'journal_id', 'author_id', 'created_at');

-- -----------------------------------------------------------------------------
-- journal_photos  (COUPLE-OWNED)
-- -----------------------------------------------------------------------------

create table public.journal_photos (
  id           uuid primary key default gen_random_uuid(),
  couple_id    uuid not null references public.couples (id) on delete cascade,
  journal_id   uuid not null,
  uploaded_by  uuid references auth.users (id) on delete set null,
  storage_path text not null unique,
  content_type text not null check (content_type in (
                 'image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif'
               )),
  size_bytes   integer check (size_bytes is null or size_bytes > 0),
  caption      text check (caption is null or char_length(caption) <= 500),
  created_at   timestamptz not null default now(),
  foreign key (journal_id, couple_id) references public.journals (id, couple_id) on delete cascade,
  constraint journal_photos_path_scoped check (
    storage_path ~ ('^couples/' || couple_id::text || '/journals/' || journal_id::text
                    || '/[0-9a-f-]{36}\.(jpg|png|webp|gif|avif)$')
  )
);

create index journal_photos_journal_idx on public.journal_photos (journal_id, created_at);
create index journal_photos_couple_created_idx on public.journal_photos (couple_id, created_at desc);

create trigger journal_photos_guard_immutable
  before update on public.journal_photos
  for each row execute function private.guard_immutable_columns(
    'couple_id', 'journal_id', 'uploaded_by', 'storage_path', 'content_type', 'size_bytes', 'created_at'
  );

-- -----------------------------------------------------------------------------
-- places + place_journals  (COUPLE-OWNED)
-- -----------------------------------------------------------------------------

create table public.places (
  id               uuid primary key default gen_random_uuid(),
  couple_id        uuid not null references public.couples (id) on delete cascade,
  created_by       uuid references auth.users (id) on delete set null,
  name             text not null check (char_length(btrim(name)) between 1 and 160),
  description      text check (description is null or char_length(description) <= 5000),
  address          text check (address is null or char_length(address) <= 300),
  latitude         double precision check (latitude is null or latitude between -90 and 90),
  longitude        double precision check (longitude is null or longitude between -180 and 180),
  category         text not null default 'other'
                   check (category in ('home', 'food', 'travel', 'nature', 'culture', 'nightlife', 'other')),
  status           text not null default 'visited' check (status in ('visited', 'wishlist')),
  first_visited_on date,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (id, couple_id)
);

create index places_couple_idx on public.places (couple_id, created_at desc);

create trigger places_set_updated_at
  before update on public.places
  for each row execute function private.set_updated_at();

create trigger places_guard_immutable
  before update on public.places
  for each row execute function private.guard_immutable_columns('couple_id', 'created_by', 'created_at');

create table public.place_journals (
  couple_id  uuid not null references public.couples (id) on delete cascade,
  place_id   uuid not null,
  journal_id uuid not null,
  created_at timestamptz not null default now(),
  primary key (place_id, journal_id),
  foreign key (place_id, couple_id) references public.places (id, couple_id) on delete cascade,
  foreign key (journal_id, couple_id) references public.journals (id, couple_id) on delete cascade
);

create index place_journals_journal_idx on public.place_journals (journal_id);

-- -----------------------------------------------------------------------------
-- events  (COUPLE-OWNED)
-- -----------------------------------------------------------------------------

create table public.events (
  id          uuid primary key default gen_random_uuid(),
  couple_id   uuid not null references public.couples (id) on delete cascade,
  created_by  uuid references auth.users (id) on delete set null,
  title       text not null check (char_length(btrim(title)) between 1 and 160),
  description text check (description is null or char_length(description) <= 5000),
  starts_at   timestamptz not null,
  ends_at     timestamptz,
  all_day     boolean not null default false,
  location    text check (location is null or char_length(location) <= 200),
  place_id    uuid,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  constraint events_valid_range check (ends_at is null or ends_at >= starts_at),
  foreign key (place_id, couple_id) references public.places (id, couple_id) on delete set null (place_id)
);

create index events_couple_starts_idx on public.events (couple_id, starts_at);

create trigger events_set_updated_at
  before update on public.events
  for each row execute function private.set_updated_at();

create trigger events_guard_immutable
  before update on public.events
  for each row execute function private.guard_immutable_columns('couple_id', 'created_by', 'created_at');

-- -----------------------------------------------------------------------------
-- milestones  (COUPLE-OWNED)
-- -----------------------------------------------------------------------------

create table public.milestones (
  id          uuid primary key default gen_random_uuid(),
  couple_id   uuid not null references public.couples (id) on delete cascade,
  created_by  uuid references auth.users (id) on delete set null,
  title       text not null check (char_length(btrim(title)) between 1 and 160),
  description text check (description is null or char_length(description) <= 5000),
  occurred_on date not null,
  icon        text not null default 'heart'
              check (icon in ('heart', 'star', 'home', 'ring', 'plane', 'gift', 'sparkles', 'flag')),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index milestones_couple_occurred_idx on public.milestones (couple_id, occurred_on desc);

create trigger milestones_set_updated_at
  before update on public.milestones
  for each row execute function private.set_updated_at();

create trigger milestones_guard_immutable
  before update on public.milestones
  for each row execute function private.guard_immutable_columns('couple_id', 'created_by', 'created_at');

-- -----------------------------------------------------------------------------
-- notes  (USER-OWNED when private, RELATIONSHIP-CONTROLLED when shared)
-- -----------------------------------------------------------------------------

create table public.notes (
  id         uuid primary key default gen_random_uuid(),
  couple_id  uuid not null references public.couples (id) on delete cascade,
  author_id  uuid not null,
  visibility text not null default 'private' check (visibility in ('private', 'shared')),
  title      text check (title is null or char_length(title) <= 160),
  body       text not null check (char_length(btrim(body)) between 1 and 20000),
  pinned     boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (couple_id, author_id) references public.couple_members (couple_id, user_id) on delete cascade
);

create index notes_couple_author_idx on public.notes (couple_id, author_id);

create trigger notes_set_updated_at
  before update on public.notes
  for each row execute function private.set_updated_at();

create trigger notes_guard_immutable
  before update on public.notes
  for each row execute function private.guard_immutable_columns('couple_id', 'author_id', 'created_at');

-- -----------------------------------------------------------------------------
-- letters + letter_contents  (USER-OWNED by the author)
--
-- The sealed content lives in its own table so that RLS — not the UI — decides
-- whether it can be read. The recipient can always see the envelope (letters
-- row: author, title, unlock_at) but letter_contents is only readable by the
-- recipient once unlock_at has passed (database clock, not client clock).
-- -----------------------------------------------------------------------------

create table public.letters (
  id           uuid primary key default gen_random_uuid(),
  couple_id    uuid not null references public.couples (id) on delete cascade,
  author_id    uuid not null,
  recipient_id uuid not null,
  -- The "envelope" line. Visible to the recipient before the letter unlocks.
  title        text not null check (char_length(btrim(title)) between 1 and 160),
  unlock_at    timestamptz not null,
  opened_at    timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (id, couple_id),
  constraint letters_distinct_people check (author_id <> recipient_id),
  foreign key (couple_id, author_id) references public.couple_members (couple_id, user_id) on delete cascade,
  foreign key (couple_id, recipient_id) references public.couple_members (couple_id, user_id) on delete cascade
);

create index letters_couple_unlock_idx on public.letters (couple_id, unlock_at);

create trigger letters_set_updated_at
  before update on public.letters
  for each row execute function private.set_updated_at();

create trigger letters_guard_immutable
  before update on public.letters
  for each row execute function private.guard_immutable_columns('couple_id', 'author_id', 'recipient_id', 'created_at');

create table public.letter_contents (
  letter_id  uuid primary key,
  couple_id  uuid not null references public.couples (id) on delete cascade,
  content    text not null check (char_length(btrim(content)) between 1 and 50000),
  updated_at timestamptz not null default now(),
  foreign key (letter_id, couple_id) references public.letters (id, couple_id) on delete cascade
);

create trigger letter_contents_set_updated_at
  before update on public.letter_contents
  for each row execute function private.set_updated_at();

create trigger letter_contents_guard_immutable
  before update on public.letter_contents
  for each row execute function private.guard_immutable_columns('letter_id', 'couple_id');

-- >>> 20260917000200_rls.sql

-- =============================================================================
-- Our Story :: 0200 row level security + privileges
--
-- The rule underneath every policy:
--
--   exists (select 1 from couple_members cm
--           where cm.couple_id = <row>.couple_id and cm.user_id = auth.uid())
--
-- implemented once in private.is_couple_member(). It is SECURITY DEFINER so it
-- can read couple_members without recursing through couple_members' own RLS,
-- and it treats soft-deleted couples as having no members.
--
-- Privileges are granted explicitly (least privilege) instead of relying on
-- Supabase's default "grant all to anon, authenticated". anon gets nothing on
-- any table; the only anonymous entry point is get_invitation_preview().
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Membership helpers
-- -----------------------------------------------------------------------------

create or replace function private.is_couple_member(p_couple_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.couple_members cm
    join public.couples c on c.id = cm.couple_id
    where cm.couple_id = p_couple_id
      and cm.user_id = (select auth.uid())
      and c.deleted_at is null
  );
$$;

-- True when the current user and p_user_id are both members of some live couple.
create or replace function private.shares_couple_with(p_user_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.couple_members me
    join public.couple_members them on them.couple_id = me.couple_id
    join public.couples c on c.id = me.couple_id
    where me.user_id = (select auth.uid())
      and them.user_id = p_user_id
      and c.deleted_at is null
  );
$$;

revoke all on all functions in schema private from public;
grant execute on all functions in schema private to authenticated, service_role;

-- -----------------------------------------------------------------------------
-- Enable RLS everywhere
-- -----------------------------------------------------------------------------

alter table public.profiles            enable row level security;
alter table public.couples             enable row level security;
alter table public.couple_members      enable row level security;
alter table public.couple_invitations  enable row level security;
alter table public.couple_themes       enable row level security;
alter table public.journals            enable row level security;
alter table public.journal_reflections enable row level security;
alter table public.journal_photos      enable row level security;
alter table public.places              enable row level security;
alter table public.place_journals      enable row level security;
alter table public.events              enable row level security;
alter table public.milestones          enable row level security;
alter table public.notes               enable row level security;
alter table public.letters             enable row level security;
alter table public.letter_contents     enable row level security;

-- -----------------------------------------------------------------------------
-- Privileges: revoke the platform defaults, then grant exactly what is used.
-- -----------------------------------------------------------------------------

revoke all on
  public.profiles, public.couples, public.couple_members, public.couple_invitations,
  public.couple_themes, public.journals, public.journal_reflections, public.journal_photos,
  public.places, public.place_journals, public.events, public.milestones, public.notes,
  public.letters, public.letter_contents
from anon, authenticated;

grant all on
  public.profiles, public.couples, public.couple_members, public.couple_invitations,
  public.couple_themes, public.journals, public.journal_reflections, public.journal_photos,
  public.places, public.place_journals, public.events, public.milestones, public.notes,
  public.letters, public.letter_contents
to service_role;

-- profiles: your own row is writable; partners' rows are readable.
grant select on public.profiles to authenticated;
grant insert (id, display_name, birthday) on public.profiles to authenticated;
grant update (display_name, birthday) on public.profiles to authenticated;

-- couples: created/deleted only through RPCs; identity fields editable by members.
grant select on public.couples to authenticated;
grant update (name, display_title, description, story_began_on, cover_path) on public.couples to authenticated;

-- couple_members: created only through RPCs; you may change your own avatar.
grant select on public.couple_members to authenticated;
grant update (avatar_path) on public.couple_members to authenticated;

-- couple_invitations: read-only for members, and token_hash is NOT readable.
grant select (
  id, couple_id, invited_email, invited_by, expires_at, accepted_at, accepted_by,
  cancelled_at, cancelled_by, last_sent_at, sends_in_window, created_at
) on public.couple_invitations to authenticated;

-- couple_themes: created by create_couple(); appearance editable by members.
grant select on public.couple_themes to authenticated;
grant update (name, primary_color, background_color, card_style, typography, background_style, layout)
  on public.couple_themes to authenticated;

-- Content tables
grant select, insert, update, delete on
  public.journals, public.journal_reflections, public.places, public.events,
  public.milestones, public.notes
to authenticated;

grant select, insert, delete on public.journal_photos to authenticated;
grant update (caption) on public.journal_photos to authenticated;

grant select, insert, delete on public.place_journals to authenticated;

grant select, insert, delete on public.letters to authenticated;
grant update (title, unlock_at) on public.letters to authenticated;
grant select, insert, update (content), delete on public.letter_contents to authenticated;

-- =============================================================================
-- Policies
-- =============================================================================

-- profiles --------------------------------------------------------------------

create policy profiles_select_self_or_partner on public.profiles
  for select to authenticated
  using (id = (select auth.uid()) or private.shares_couple_with(id));

create policy profiles_insert_self on public.profiles
  for insert to authenticated
  with check (id = (select auth.uid()));

create policy profiles_update_self on public.profiles
  for update to authenticated
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

-- couples ---------------------------------------------------------------------

create policy couples_select_member on public.couples
  for select to authenticated
  using (private.is_couple_member(id));

create policy couples_update_member on public.couples
  for update to authenticated
  using (private.is_couple_member(id))
  with check (private.is_couple_member(id));

-- couple_members --------------------------------------------------------------

create policy couple_members_select_member on public.couple_members
  for select to authenticated
  using (private.is_couple_member(couple_id));

create policy couple_members_update_own on public.couple_members
  for update to authenticated
  using (user_id = (select auth.uid()) and private.is_couple_member(couple_id))
  with check (user_id = (select auth.uid()) and private.is_couple_member(couple_id));

-- couple_invitations ----------------------------------------------------------

create policy couple_invitations_select_member on public.couple_invitations
  for select to authenticated
  using (private.is_couple_member(couple_id));

-- couple_themes ---------------------------------------------------------------

create policy couple_themes_select_member on public.couple_themes
  for select to authenticated
  using (private.is_couple_member(couple_id));

create policy couple_themes_update_member on public.couple_themes
  for update to authenticated
  using (private.is_couple_member(couple_id))
  with check (private.is_couple_member(couple_id));

-- Couple-owned content: any member of the couple has full access. ---------------

create policy journals_select_member on public.journals
  for select to authenticated using (private.is_couple_member(couple_id));
create policy journals_insert_member on public.journals
  for insert to authenticated
  with check (private.is_couple_member(couple_id) and created_by = (select auth.uid()));
create policy journals_update_member on public.journals
  for update to authenticated
  using (private.is_couple_member(couple_id)) with check (private.is_couple_member(couple_id));
create policy journals_delete_member on public.journals
  for delete to authenticated using (private.is_couple_member(couple_id));

create policy journal_photos_select_member on public.journal_photos
  for select to authenticated using (private.is_couple_member(couple_id));
create policy journal_photos_insert_member on public.journal_photos
  for insert to authenticated
  with check (private.is_couple_member(couple_id) and uploaded_by = (select auth.uid()));
create policy journal_photos_update_member on public.journal_photos
  for update to authenticated
  using (private.is_couple_member(couple_id)) with check (private.is_couple_member(couple_id));
create policy journal_photos_delete_member on public.journal_photos
  for delete to authenticated using (private.is_couple_member(couple_id));

create policy places_select_member on public.places
  for select to authenticated using (private.is_couple_member(couple_id));
create policy places_insert_member on public.places
  for insert to authenticated
  with check (private.is_couple_member(couple_id) and created_by = (select auth.uid()));
create policy places_update_member on public.places
  for update to authenticated
  using (private.is_couple_member(couple_id)) with check (private.is_couple_member(couple_id));
create policy places_delete_member on public.places
  for delete to authenticated using (private.is_couple_member(couple_id));

create policy place_journals_select_member on public.place_journals
  for select to authenticated using (private.is_couple_member(couple_id));
create policy place_journals_insert_member on public.place_journals
  for insert to authenticated with check (private.is_couple_member(couple_id));
create policy place_journals_delete_member on public.place_journals
  for delete to authenticated using (private.is_couple_member(couple_id));

create policy events_select_member on public.events
  for select to authenticated using (private.is_couple_member(couple_id));
create policy events_insert_member on public.events
  for insert to authenticated
  with check (private.is_couple_member(couple_id) and created_by = (select auth.uid()));
create policy events_update_member on public.events
  for update to authenticated
  using (private.is_couple_member(couple_id)) with check (private.is_couple_member(couple_id));
create policy events_delete_member on public.events
  for delete to authenticated using (private.is_couple_member(couple_id));

create policy milestones_select_member on public.milestones
  for select to authenticated using (private.is_couple_member(couple_id));
create policy milestones_insert_member on public.milestones
  for insert to authenticated
  with check (private.is_couple_member(couple_id) and created_by = (select auth.uid()));
create policy milestones_update_member on public.milestones
  for update to authenticated
  using (private.is_couple_member(couple_id)) with check (private.is_couple_member(couple_id));
create policy milestones_delete_member on public.milestones
  for delete to authenticated using (private.is_couple_member(couple_id));

-- Private-or-shared content: tenant isolation AND content privacy. -----------------
--   private -> member of couple AND author
--   shared  -> member of couple AND visibility = 'shared'
-- Only the author may write.

create policy journal_reflections_select on public.journal_reflections
  for select to authenticated
  using (
    private.is_couple_member(couple_id)
    and (author_id = (select auth.uid()) or visibility = 'shared')
  );
create policy journal_reflections_insert_author on public.journal_reflections
  for insert to authenticated
  with check (private.is_couple_member(couple_id) and author_id = (select auth.uid()));
create policy journal_reflections_update_author on public.journal_reflections
  for update to authenticated
  using (private.is_couple_member(couple_id) and author_id = (select auth.uid()))
  with check (private.is_couple_member(couple_id) and author_id = (select auth.uid()));
create policy journal_reflections_delete_author on public.journal_reflections
  for delete to authenticated
  using (private.is_couple_member(couple_id) and author_id = (select auth.uid()));

create policy notes_select on public.notes
  for select to authenticated
  using (
    private.is_couple_member(couple_id)
    and (author_id = (select auth.uid()) or visibility = 'shared')
  );
create policy notes_insert_author on public.notes
  for insert to authenticated
  with check (private.is_couple_member(couple_id) and author_id = (select auth.uid()));
create policy notes_update_author on public.notes
  for update to authenticated
  using (private.is_couple_member(couple_id) and author_id = (select auth.uid()))
  with check (private.is_couple_member(couple_id) and author_id = (select auth.uid()));
create policy notes_delete_author on public.notes
  for delete to authenticated
  using (private.is_couple_member(couple_id) and author_id = (select auth.uid()));

-- Letters ------------------------------------------------------------------------
-- Envelope (letters): visible to author and recipient.
-- Only the author edits, and only while the letter is still sealed.
-- opened_at is set through public.mark_letter_opened().

create policy letters_select_participants on public.letters
  for select to authenticated
  using (
    private.is_couple_member(couple_id)
    and (author_id = (select auth.uid()) or recipient_id = (select auth.uid()))
  );
create policy letters_insert_author on public.letters
  for insert to authenticated
  with check (private.is_couple_member(couple_id) and author_id = (select auth.uid()));
create policy letters_update_author_while_sealed on public.letters
  for update to authenticated
  using (
    private.is_couple_member(couple_id)
    and author_id = (select auth.uid())
    and unlock_at > now()
  )
  with check (private.is_couple_member(couple_id) and author_id = (select auth.uid()));
create policy letters_delete_author on public.letters
  for delete to authenticated
  using (private.is_couple_member(couple_id) and author_id = (select auth.uid()));

-- Sealed content: the author always; the recipient only once unlock_at <= now().
create policy letter_contents_select on public.letter_contents
  for select to authenticated
  using (
    private.is_couple_member(couple_id)
    and exists (
      select 1 from public.letters l
      where l.id = letter_contents.letter_id
        and (
          l.author_id = (select auth.uid())
          or (l.recipient_id = (select auth.uid()) and l.unlock_at <= now())
        )
    )
  );
create policy letter_contents_insert_author on public.letter_contents
  for insert to authenticated
  with check (
    private.is_couple_member(couple_id)
    and exists (
      select 1 from public.letters l
      where l.id = letter_contents.letter_id and l.author_id = (select auth.uid())
    )
  );
create policy letter_contents_update_author_while_sealed on public.letter_contents
  for update to authenticated
  using (
    private.is_couple_member(couple_id)
    and exists (
      select 1 from public.letters l
      where l.id = letter_contents.letter_id
        and l.author_id = (select auth.uid())
        and l.unlock_at > now()
    )
  )
  with check (private.is_couple_member(couple_id));
create policy letter_contents_delete_author on public.letter_contents
  for delete to authenticated
  using (
    private.is_couple_member(couple_id)
    and exists (
      select 1 from public.letters l
      where l.id = letter_contents.letter_id and l.author_id = (select auth.uid())
    )
  );

-- >>> 20260917000300_functions.sql

-- =============================================================================
-- Our Story :: 0300 RPC functions
--
-- Multi-row operations that must be atomic, or that need to act before the
-- caller is a member (creating a couple, accepting an invitation), live here.
--
-- Conventions
--   * SECURITY DEFINER functions re-derive the caller from auth.uid() and
--     re-check membership themselves. They never trust a couple_id without
--     verifying the caller belongs to it.
--   * Errors are raised as a stable machine code in the message
--     (e.g. 'invitation_expired'); the app maps codes to user-facing copy.
--   * search_path is pinned to '' and every object is schema-qualified.
--   * Raw invitation tokens are accepted as arguments only to be hashed; token
--     hashes supplied on create/resend are generated server-side by the app.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Internal helpers
-- -----------------------------------------------------------------------------

create or replace function private.invitation_ttl(p_days integer)
returns interval
language sql
immutable
set search_path = ''
as $$
  select make_interval(days => least(greatest(coalesce(p_days, 7), 1), 30));
$$;

create or replace function private.normalize_email(p_email text)
returns text
language plpgsql
immutable
set search_path = ''
as $$
declare
  v_email text := lower(btrim(coalesce(p_email, '')));
begin
  if char_length(v_email) > 254 or v_email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    raise exception 'invalid_email';
  end if;
  return v_email;
end;
$$;

create or replace function private.assert_token_hash(p_token_hash text)
returns void
language plpgsql
immutable
set search_path = ''
as $$
begin
  if p_token_hash is null or p_token_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'invalid_token_hash';
  end if;
end;
$$;

-- Human label for a couple, used in invitation copy.
create or replace function private.couple_label(p_couple_id uuid)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    c.name,
    (select string_agg(p.display_name, ' & ' order by cm.joined_at)
       from public.couple_members cm
       join public.profiles p on p.id = cm.user_id
      where cm.couple_id = c.id),
    'Our Story'
  )
  from public.couples c
  where c.id = p_couple_id;
$$;

revoke all on all functions in schema private from public;
grant execute on all functions in schema private to authenticated, service_role;

-- -----------------------------------------------------------------------------
-- create_couple: onboarding. Profile + couple + membership + theme + invitation.
-- -----------------------------------------------------------------------------

create or replace function public.create_couple(
  p_creator_name      text,
  p_partner_email     text,
  p_invite_token_hash text,
  p_couple_name       text default null,
  p_story_began_on    date default null,
  p_invite_ttl_days   integer default 7
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid           uuid := auth.uid();
  v_user_email    text;
  v_creator_name  text := btrim(coalesce(p_creator_name, ''));
  v_couple_name   text := nullif(btrim(coalesce(p_couple_name, '')), '');
  v_partner_email text;
  v_couple_id     uuid;
  v_invitation_id uuid;
  v_expires_at    timestamptz;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;

  select lower(email) into v_user_email from auth.users where id = v_uid;

  if char_length(v_creator_name) not between 1 and 60 then
    raise exception 'invalid_name';
  end if;
  if v_couple_name is not null and char_length(v_couple_name) > 80 then
    raise exception 'invalid_couple_name';
  end if;

  v_partner_email := private.normalize_email(p_partner_email);
  if v_partner_email = v_user_email then
    raise exception 'cannot_invite_self';
  end if;

  perform private.assert_token_hash(p_invite_token_hash);

  if (select count(*)
        from public.couple_members cm
        join public.couples c on c.id = cm.couple_id
       where cm.user_id = v_uid and c.deleted_at is null) >= 5 then
    raise exception 'membership_limit_reached';
  end if;

  if (select count(*) from public.couples
       where created_by = v_uid and created_at > now() - interval '24 hours') >= 3 then
    raise exception 'rate_limited';
  end if;

  insert into public.profiles (id, display_name)
  values (v_uid, v_creator_name)
  on conflict (id) do update set display_name = excluded.display_name;

  insert into public.couples (slug, name, story_began_on, created_by)
  values (
    private.slugify(coalesce(v_couple_name, v_creator_name))
      || '-' || left(replace(gen_random_uuid()::text, '-', ''), 8),
    v_couple_name,
    p_story_began_on,
    v_uid
  )
  returning id into v_couple_id;

  insert into public.couple_members (couple_id, user_id, role)
  values (v_couple_id, v_uid, 'creator');

  insert into public.couple_themes (couple_id) values (v_couple_id);

  v_expires_at := now() + private.invitation_ttl(p_invite_ttl_days);

  insert into public.couple_invitations (couple_id, invited_email, invited_by, token_hash, expires_at)
  values (v_couple_id, v_partner_email, v_uid, p_invite_token_hash, v_expires_at)
  returning id into v_invitation_id;

  return jsonb_build_object(
    'couple_id',     v_couple_id,
    'invitation_id', v_invitation_id,
    'invited_email', v_partner_email,
    'expires_at',    v_expires_at,
    'inviter_name',  v_creator_name,
    'couple_label',  coalesce(v_couple_name, v_creator_name)
  );
end;
$$;

-- -----------------------------------------------------------------------------
-- get_invitation_preview: the only anonymous entry point.
-- Returns just enough to render the invitation page for the token holder.
-- -----------------------------------------------------------------------------

create or replace function public.get_invitation_preview(p_token text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_uid         uuid := auth.uid();
  v_inv         public.couple_invitations%rowtype;
  v_couple      public.couples%rowtype;
  v_member_cnt  integer;
  v_inviter     text;
  v_viewer_mail text;
  v_status      text;
begin
  if p_token is null or char_length(p_token) not between 32 and 128 then
    return jsonb_build_object('status', 'not_found');
  end if;

  select * into v_inv
    from public.couple_invitations
   where token_hash = private.hash_invitation_token(p_token);

  if not found then
    return jsonb_build_object('status', 'not_found');
  end if;

  select * into v_couple from public.couples where id = v_inv.couple_id;
  select count(*) into v_member_cnt from public.couple_members where couple_id = v_inv.couple_id;
  select display_name into v_inviter from public.profiles where id = v_inv.invited_by;

  if v_uid is not null then
    select lower(email) into v_viewer_mail from auth.users where id = v_uid;
  end if;

  v_status := case
    when v_couple.id is null or v_couple.deleted_at is not null then 'unavailable'
    when v_uid is not null and exists (
      select 1 from public.couple_members
       where couple_id = v_inv.couple_id and user_id = v_uid
    ) then 'already_member'
    when v_inv.cancelled_at is not null then 'cancelled'
    when v_inv.accepted_at is not null then 'accepted'
    when v_member_cnt >= 2 then 'full'
    when v_inv.expires_at <= now() then 'expired'
    else 'valid'
  end;

  if v_status <> 'valid' then
    return jsonb_build_object(
      'status',       v_status,
      'inviter_name', case when v_status in ('expired', 'already_member') then v_inviter end
    );
  end if;

  return jsonb_build_object(
    'status',               'valid',
    'inviter_name',         coalesce(v_inviter, 'Your partner'),
    'couple_label',         private.couple_label(v_inv.couple_id),
    'display_title',        v_couple.display_title,
    'invited_email',        v_inv.invited_email,
    'expires_at',           v_inv.expires_at,
    'viewer_email_matches', case when v_uid is null then null else v_viewer_mail = v_inv.invited_email end
  );
end;
$$;

-- -----------------------------------------------------------------------------
-- accept_couple_invitation
-- -----------------------------------------------------------------------------

create or replace function public.accept_couple_invitation(
  p_token        text,
  p_display_name text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid        uuid := auth.uid();
  v_user       auth.users%rowtype;
  v_inv        public.couple_invitations%rowtype;
  v_name       text := nullif(btrim(coalesce(p_display_name, '')), '');
  v_member_cnt integer;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;
  if p_token is null or char_length(p_token) not between 32 and 128 then
    raise exception 'invitation_not_found';
  end if;
  if v_name is not null and char_length(v_name) > 60 then
    raise exception 'invalid_name';
  end if;

  select * into v_user from auth.users where id = v_uid;

  -- Email ownership must be proven before joining someone's space.
  if v_user.email_confirmed_at is null then
    raise exception 'email_not_confirmed';
  end if;

  select * into v_inv
    from public.couple_invitations
   where token_hash = private.hash_invitation_token(p_token)
   for update;

  if not found then
    raise exception 'invitation_not_found';
  end if;

  -- The invitation is bound to one email address.
  if lower(v_user.email) <> v_inv.invited_email then
    raise exception 'invitation_email_mismatch';
  end if;

  if v_inv.cancelled_at is not null then
    raise exception 'invitation_cancelled';
  end if;

  if v_inv.accepted_at is not null then
    -- Idempotent for the person who already accepted it (double submit).
    if v_inv.accepted_by = v_uid and exists (
      select 1 from public.couple_members where couple_id = v_inv.couple_id and user_id = v_uid
    ) then
      return jsonb_build_object('couple_id', v_inv.couple_id);
    end if;
    raise exception 'invitation_already_accepted';
  end if;

  if v_inv.expires_at <= now() then
    raise exception 'invitation_expired';
  end if;

  -- Lock the tenant so the two-member check cannot race.
  perform 1 from public.couples where id = v_inv.couple_id and deleted_at is null for update;
  if not found then
    raise exception 'couple_unavailable';
  end if;

  if exists (select 1 from public.couple_members where couple_id = v_inv.couple_id and user_id = v_uid) then
    update public.couple_invitations
       set accepted_at = now(), accepted_by = v_uid
     where id = v_inv.id;
    return jsonb_build_object('couple_id', v_inv.couple_id);
  end if;

  select count(*) into v_member_cnt from public.couple_members where couple_id = v_inv.couple_id;
  if v_member_cnt >= 2 then
    raise exception 'couple_full';
  end if;

  if (select count(*)
        from public.couple_members cm
        join public.couples c on c.id = cm.couple_id
       where cm.user_id = v_uid and c.deleted_at is null) >= 5 then
    raise exception 'membership_limit_reached';
  end if;

  insert into public.profiles (id, display_name)
  values (
    v_uid,
    left(coalesce(
      v_name,
      nullif(btrim(v_user.raw_user_meta_data ->> 'display_name'), ''),
      split_part(v_user.email, '@', 1)
    ), 60)
  )
  on conflict (id) do update
    set display_name = coalesce(v_name, public.profiles.display_name);

  insert into public.couple_members (couple_id, user_id, role)
  values (v_inv.couple_id, v_uid, 'partner');

  update public.couple_invitations
     set accepted_at = now(), accepted_by = v_uid
   where id = v_inv.id;

  return jsonb_build_object('couple_id', v_inv.couple_id);
end;
$$;

-- -----------------------------------------------------------------------------
-- create_couple_invitation: invite (or re-invite a different email) from settings.
-- Any existing open invitation for the couple is cancelled first.
-- -----------------------------------------------------------------------------

create or replace function public.create_couple_invitation(
  p_couple_id     uuid,
  p_invited_email text,
  p_token_hash    text,
  p_ttl_days      integer default 7
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid           uuid := auth.uid();
  v_email         text;
  v_invitation_id uuid;
  v_expires_at    timestamptz;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;
  if not private.is_couple_member(p_couple_id) then
    raise exception 'couple_not_found';
  end if;

  v_email := private.normalize_email(p_invited_email);
  perform private.assert_token_hash(p_token_hash);

  perform 1 from public.couples where id = p_couple_id for update;

  if (select count(*) from public.couple_members where couple_id = p_couple_id) >= 2 then
    raise exception 'couple_full';
  end if;

  if exists (
    select 1 from public.couple_members cm
      join auth.users u on u.id = cm.user_id
     where cm.couple_id = p_couple_id and lower(u.email) = v_email
  ) then
    raise exception 'cannot_invite_member';
  end if;

  if (select count(*) from public.couple_invitations
       where couple_id = p_couple_id and created_at > now() - interval '24 hours') >= 5 then
    raise exception 'rate_limited';
  end if;

  update public.couple_invitations
     set cancelled_at = now(), cancelled_by = v_uid
   where couple_id = p_couple_id and accepted_at is null and cancelled_at is null;

  v_expires_at := now() + private.invitation_ttl(p_ttl_days);

  insert into public.couple_invitations (couple_id, invited_email, invited_by, token_hash, expires_at)
  values (p_couple_id, v_email, v_uid, p_token_hash, v_expires_at)
  returning id into v_invitation_id;

  return jsonb_build_object(
    'invitation_id', v_invitation_id,
    'invited_email', v_email,
    'expires_at',    v_expires_at,
    'inviter_name',  (select display_name from public.profiles where id = v_uid),
    'couple_label',  private.couple_label(p_couple_id)
  );
end;
$$;

-- -----------------------------------------------------------------------------
-- resend_couple_invitation: rotates the token (old link dies), renews expiry.
-- Rate limited: at least 60 seconds apart and at most 5 sends per 24 hours.
-- -----------------------------------------------------------------------------

create or replace function public.resend_couple_invitation(
  p_invitation_id uuid,
  p_token_hash    text,
  p_ttl_days      integer default 7
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid        uuid := auth.uid();
  v_inv        public.couple_invitations%rowtype;
  v_window_at  timestamptz;
  v_sends      integer;
  v_expires_at timestamptz;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;
  perform private.assert_token_hash(p_token_hash);

  select * into v_inv from public.couple_invitations where id = p_invitation_id for update;

  -- Non-members get the same answer as a missing invitation.
  if not found or not private.is_couple_member(v_inv.couple_id) then
    raise exception 'invitation_not_found';
  end if;
  if v_inv.accepted_at is not null then
    raise exception 'invitation_already_accepted';
  end if;
  if v_inv.cancelled_at is not null then
    raise exception 'invitation_cancelled';
  end if;
  if (select count(*) from public.couple_members where couple_id = v_inv.couple_id) >= 2 then
    raise exception 'couple_full';
  end if;

  if v_inv.last_sent_at > now() - interval '60 seconds' then
    raise exception 'resend_too_soon'
      using hint = ceil(extract(epoch from (v_inv.last_sent_at + interval '60 seconds' - now())))::text;
  end if;

  if v_inv.send_window_started_at <= now() - interval '24 hours' then
    v_window_at := now();
    v_sends := 0;
  else
    v_window_at := v_inv.send_window_started_at;
    v_sends := v_inv.sends_in_window;
  end if;

  if v_sends >= 5 then
    raise exception 'resend_limit_reached'
      using hint = ceil(extract(epoch from (v_window_at + interval '24 hours' - now())))::text;
  end if;

  v_expires_at := now() + private.invitation_ttl(p_ttl_days);

  update public.couple_invitations
     set token_hash             = p_token_hash,
         expires_at             = v_expires_at,
         last_sent_at           = now(),
         send_window_started_at = v_window_at,
         sends_in_window        = v_sends + 1
   where id = v_inv.id;

  return jsonb_build_object(
    'invitation_id', v_inv.id,
    'invited_email', v_inv.invited_email,
    'expires_at',    v_expires_at,
    'inviter_name',  (select display_name from public.profiles where id = v_uid),
    'couple_label',  private.couple_label(v_inv.couple_id)
  );
end;
$$;

-- -----------------------------------------------------------------------------
-- cancel_couple_invitation: the old token stops working immediately.
-- -----------------------------------------------------------------------------

create or replace function public.cancel_couple_invitation(p_invitation_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
  v_inv public.couple_invitations%rowtype;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;

  select * into v_inv from public.couple_invitations where id = p_invitation_id for update;

  if not found or not private.is_couple_member(v_inv.couple_id) then
    raise exception 'invitation_not_found';
  end if;
  if v_inv.accepted_at is not null then
    raise exception 'invitation_already_accepted';
  end if;
  if v_inv.cancelled_at is not null then
    return;
  end if;

  update public.couple_invitations
     set cancelled_at = now(), cancelled_by = v_uid
   where id = v_inv.id;
end;
$$;

-- -----------------------------------------------------------------------------
-- delete_couple: destructive. Soft-deletes the tenant (all content becomes
-- unreachable for everyone) and requires an explicit confirmation phrase.
-- -----------------------------------------------------------------------------

create or replace function public.delete_couple(p_couple_id uuid, p_confirmation text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := auth.uid();
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;
  if not private.is_couple_member(p_couple_id) then
    raise exception 'couple_not_found';
  end if;
  if p_confirmation is distinct from 'DELETE OUR SPACE' then
    raise exception 'confirmation_mismatch';
  end if;

  update public.couple_invitations
     set cancelled_at = now(), cancelled_by = v_uid
   where couple_id = p_couple_id and accepted_at is null and cancelled_at is null;

  update public.couples set deleted_at = now() where id = p_couple_id;
end;
$$;

-- -----------------------------------------------------------------------------
-- Letters. SECURITY INVOKER: every statement runs under the caller's RLS.
-- The recipient is derived from membership, never supplied by the client.
-- -----------------------------------------------------------------------------

create or replace function public.create_letter(
  p_couple_id uuid,
  p_title     text,
  p_content   text,
  p_unlock_at timestamptz
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_uid       uuid := auth.uid();
  v_recipient uuid;
  v_letter_id uuid;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;
  if not private.is_couple_member(p_couple_id) then
    raise exception 'couple_not_found';
  end if;
  if p_unlock_at is null then
    raise exception 'invalid_unlock_at';
  end if;

  select user_id into v_recipient
    from public.couple_members
   where couple_id = p_couple_id and user_id <> v_uid
   limit 1;

  if v_recipient is null then
    raise exception 'partner_not_joined';
  end if;

  insert into public.letters (couple_id, author_id, recipient_id, title, unlock_at)
  values (p_couple_id, v_uid, v_recipient, btrim(p_title), p_unlock_at)
  returning id into v_letter_id;

  insert into public.letter_contents (letter_id, couple_id, content)
  values (v_letter_id, p_couple_id, p_content);

  return v_letter_id;
end;
$$;

create or replace function public.update_letter(
  p_letter_id uuid,
  p_title     text,
  p_content   text,
  p_unlock_at timestamptz
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'not_authenticated';
  end if;

  -- Content first: its policy checks the letter is still sealed, which must be
  -- evaluated against the current unlock_at, before it is changed below.
  update public.letter_contents set content = p_content where letter_id = p_letter_id;
  if not found then
    raise exception 'letter_not_editable';
  end if;

  update public.letters
     set title = btrim(p_title), unlock_at = p_unlock_at
   where id = p_letter_id;
  if not found then
    raise exception 'letter_not_editable';
  end if;
end;
$$;

create or replace function public.mark_letter_opened(p_letter_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.letters
     set opened_at = now()
   where id = p_letter_id
     and recipient_id = auth.uid()
     and unlock_at <= now()
     and opened_at is null
     and private.is_couple_member(couple_id);
end;
$$;

-- -----------------------------------------------------------------------------
-- get_auth_account_state: SERVICE ROLE ONLY. Lets the server decide how to
-- deliver an invitation through Supabase Auth (invite email for new or
-- unverified addresses, sign-in link for existing accounts). Never exposed to
-- anon/authenticated, so it cannot be used to enumerate accounts.
-- -----------------------------------------------------------------------------

create or replace function public.get_auth_account_state(p_email text)
returns text
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (select case when u.email_confirmed_at is null then 'unconfirmed' else 'confirmed' end
       from auth.users u
      where lower(u.email) = lower(btrim(p_email))
      limit 1),
    'none'
  );
$$;

-- -----------------------------------------------------------------------------
-- Function privileges. Postgres grants EXECUTE to PUBLIC by default and
-- Supabase adds anon/authenticated, so start from zero.
-- -----------------------------------------------------------------------------

revoke all on function public.create_couple(text, text, text, text, date, integer) from public, anon, authenticated;
revoke all on function public.get_invitation_preview(text) from public, anon, authenticated;
revoke all on function public.accept_couple_invitation(text, text) from public, anon, authenticated;
revoke all on function public.create_couple_invitation(uuid, text, text, integer) from public, anon, authenticated;
revoke all on function public.resend_couple_invitation(uuid, text, integer) from public, anon, authenticated;
revoke all on function public.cancel_couple_invitation(uuid) from public, anon, authenticated;
revoke all on function public.delete_couple(uuid, text) from public, anon, authenticated;
revoke all on function public.create_letter(uuid, text, text, timestamptz) from public, anon, authenticated;
revoke all on function public.update_letter(uuid, text, text, timestamptz) from public, anon, authenticated;
revoke all on function public.mark_letter_opened(uuid) from public, anon, authenticated;
revoke all on function public.get_auth_account_state(text) from public, anon, authenticated;

grant execute on function public.get_invitation_preview(text) to anon, authenticated;
grant execute on function public.create_couple(text, text, text, text, date, integer) to authenticated;
grant execute on function public.accept_couple_invitation(text, text) to authenticated;
grant execute on function public.create_couple_invitation(uuid, text, text, integer) to authenticated;
grant execute on function public.resend_couple_invitation(uuid, text, integer) to authenticated;
grant execute on function public.cancel_couple_invitation(uuid) to authenticated;
grant execute on function public.delete_couple(uuid, text) to authenticated;
grant execute on function public.create_letter(uuid, text, text, timestamptz) to authenticated;
grant execute on function public.update_letter(uuid, text, text, timestamptz) to authenticated;
grant execute on function public.mark_letter_opened(uuid) to authenticated;

grant execute on all functions in schema public to service_role;

-- >>> 20260917000400_storage.sql

-- =============================================================================
-- Our Story :: 0400 storage
--
-- One private bucket. Every object lives under its tenant prefix:
--
--   couples/{couple_id}/cover/{uuid}.{ext}
--   couples/{couple_id}/avatars/{user_id}/{uuid}.{ext}
--   couples/{couple_id}/journals/{journal_id}/{uuid}.{ext}
--
-- Object names must match that grammar exactly (lowercase UUIDs, server
-- generated file names, allow-listed image extensions), so user-supplied file
-- names and path traversal ("..", extra segments, odd characters) are rejected
-- by the policy itself. Knowing another couple's UUID grants nothing: every
-- policy re-checks membership of the couple named in the path.
--
-- The bucket enforces MIME type and size limits server-side as well. SVG is
-- intentionally not allowed (it can carry script).
-- =============================================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'couple-media',
  'couple-media',
  false,
  15 * 1024 * 1024,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/avif']
)
on conflict (id) do update
  set public             = false,
      file_size_limit    = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- Parses an object name. Returns null for anything that is not a valid path.
create or replace function private.parse_media_path(p_name text)
returns table (couple_id uuid, area text, owner_segment uuid)
language sql
immutable
set search_path = ''
as $$
  select
    m[1]::uuid,
    m[2],
    m[3]::uuid
  from regexp_match(
    p_name,
    '^couples/([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/'
    || '(cover|avatars|journals)/'
    || '(?:([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/)?'
    || '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'
    || '\.(jpg|png|webp|gif|avif)$'
  ) as m
  where m is not null
    -- cover has no owner segment; avatars and journals require one.
    and ((m[2] = 'cover') = (m[3] is null));
$$;

create or replace function private.can_read_media(p_name text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(
    (select private.is_couple_member(p.couple_id) from private.parse_media_path(p_name) p),
    false
  );
$$;

create or replace function private.can_upload_media(p_name text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((
    select private.is_couple_member(p.couple_id)
       and case p.area
             when 'cover'    then true
             -- You can only upload your own avatar.
             when 'avatars'  then p.owner_segment = (select auth.uid())
             -- The journal must exist and belong to the same couple.
             when 'journals' then exists (
               select 1 from public.journals j
                where j.id = p.owner_segment and j.couple_id = p.couple_id
             )
             else false
           end
    from private.parse_media_path(p_name) p
  ), false);
$$;

create or replace function private.can_delete_media(p_name text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  -- No journal-existence check: photos are removed after their journal row.
  select coalesce((
    select private.is_couple_member(p.couple_id)
       and (p.area <> 'avatars' or p.owner_segment = (select auth.uid()))
    from private.parse_media_path(p_name) p
  ), false);
$$;

revoke all on all functions in schema private from public;
grant execute on all functions in schema private to authenticated, service_role;

drop policy if exists couple_media_select on storage.objects;
drop policy if exists couple_media_insert on storage.objects;
drop policy if exists couple_media_delete on storage.objects;

create policy couple_media_select on storage.objects
  for select to authenticated
  using (bucket_id = 'couple-media' and private.can_read_media(name));

create policy couple_media_insert on storage.objects
  for insert to authenticated
  with check (bucket_id = 'couple-media' and private.can_upload_media(name));

create policy couple_media_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'couple-media' and private.can_delete_media(name));

-- No UPDATE policy: objects are immutable (no upsert/overwrite, no move).

-- >>> 20260917000500_photo_thumbnails.sql

-- =============================================================================
-- Our Story :: 0500 photo thumbnails
--
-- Grids and timelines show a small thumbnail instead of the full original.
-- The browser generates the thumbnail at upload time and stores it next to the
-- original, in the same tenant folder:
--
--   couples/{couple_id}/journals/{journal_id}/{uuid}.{ext}    original (storage_path)
--   couples/{couple_id}/journals/{journal_id}/{uuid}.webp     thumbnail (thumb_path)
--
-- width/height are the original's display dimensions, so layouts can reserve
-- space before the image arrives. Members cannot change these columns after
-- insert (only `caption` is granted for update).
-- =============================================================================

alter table public.journal_photos
  add column if not exists thumb_path text unique,
  add column if not exists width integer check (width is null or width between 1 and 20000),
  add column if not exists height integer check (height is null or height between 1 and 20000);

alter table public.journal_photos
  drop constraint if exists journal_photos_thumb_path_scoped;

alter table public.journal_photos
  add constraint journal_photos_thumb_path_scoped check (
    thumb_path is null
    or (
      thumb_path <> storage_path
      and thumb_path ~ ('^couples/' || couple_id::text || '/journals/' || journal_id::text
                        || '/[0-9a-f-]{36}\.(jpg|png|webp|gif|avif)$')
    )
  );

-- >>> 20260917000600_scrapbook_and_glass_theme.sql

-- =============================================================================
-- Our Story :: 0600 scrapbook pages + glass/aurora theme options
--
-- 1. Each journal entry can carry a scrapbook page: a JSON document describing
--    the paper and the placed elements (photos, stickers, notes, washi tape).
--    It lives on the journal row, so the existing journal RLS applies: both
--    members of the couple can view and edit it, nobody else can see it.
--    The app validates its shape; the database caps its size.
--    scrapbook_updated_at lets the app detect when both partners edited at once.
--
-- 2. New theme options: "glass" cards and "aurora"/"retro" backgrounds.
--    Couples still on the original defaults move to the new defaults.
-- =============================================================================

alter table public.journals
  add column if not exists scrapbook jsonb,
  add column if not exists scrapbook_updated_at timestamptz,
  add column if not exists scrapbook_updated_by uuid references auth.users (id) on delete set null;

alter table public.journals
  drop constraint if exists journals_scrapbook_shape;

alter table public.journals
  add constraint journals_scrapbook_shape check (
    scrapbook is null
    or (jsonb_typeof(scrapbook) = 'object' and pg_column_size(scrapbook) <= 262144)
  );

alter table public.couple_themes
  drop constraint if exists couple_themes_card_style_check,
  drop constraint if exists couple_themes_background_style_check;

alter table public.couple_themes
  add constraint couple_themes_card_style_check
    check (card_style in ('glass', 'soft', 'flat', 'outlined', 'elevated')),
  add constraint couple_themes_background_style_check
    check (background_style in ('aurora', 'retro', 'plain', 'paper', 'grain', 'gradient'));

alter table public.couple_themes
  alter column card_style set default 'glass',
  alter column background_style set default 'aurora';

update public.couple_themes
   set card_style = 'glass', background_style = 'aurora'
 where card_style = 'soft' and background_style = 'paper';

commit;
